config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :staffs

  devise_scope :staff do
    root to: "staffs/sessions#new"
  end
  
  get 'welcome', to: "home#welcome"

  resources :transactions do
    member do
      put :approve
      put :reject
    end
  end

  namespace :api, :defaults => {:format => :json} do
    post 'register', to: 'users#create'
    get 'transactions', to: 'transactions#index'
    post 'transactions/top_up', to: 'transactions#top_up'
    post 'transactions/withdraw', to: 'transactions#withdraw'
    post 'transactions/buy', to: 'transactions#buy'
    post 'transactions/sell', to: 'transactions#sell'
    get 'balance', to: 'balances#show'

    devise_for :users, controllers: {
      sessions: 'users/sessions'
    }
  end

  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/api/transactions_controller.rb
module Api 
  class TransactionsController < ApiController

    def index
      render json: {transactions: Transaction.represent_all}
    end

    def top_up
      transaction = initial_transaction(cash_params[:amount], 'top_up', 'cash')
      if transaction.save
        render json: { result: 'ok', name: transaction.name }
      else
        render json: { message: transaction.errors.full_messages.join(',')}, status: 400
      end
    end

    def withdraw
      transaction = initial_transaction(cash_params[:amount], 'withdraw', 'cash')
      if transaction.save
        render json: { result: 'ok', name: transaction.name }
      else
        render json: { message: transaction.errors.full_messages.join(',')}, status: 400
      end
    end

    def buy
      transaction = initial_transaction(asset_params[:amount], 'buy', asset_params[:asset])
      if transaction.save
        render json: { result: 'ok', name: transaction.name }
      else
        render json: { message: transaction.errors.full_messages.join(',')}, status: 400
      end
    end

    def sell
      transaction = initial_transaction(asset_params[:amount], 'sell', asset_params[:asset])
      if transaction.save
        render json: { result: 'ok', name: transaction.name }
      else
        render json: { message: transaction.errors.full_messages.join(',')}, status: 400
      end
    end

    private
    def initial_transaction(amount, type, asset)
      transaction = Transaction.new(
        income_amount: amount,
        transaction_type: type,
        asset_type: asset,
        user_id: current_api_user.id
      )
    end

    def cash_params
      params.permit(:amount)
    end
    
    def asset_params
      params.permit(:amount, :asset)
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_staff!
  before_action :get_transaction, only: [:approve, :reject]

  def index
    @transactions = Transaction.by_cash.where(status: 'pending').includes(:transaction_transfers).order(created_at: :desc)
    @completed_transactions = Transaction.by_cash.where(status: 'completed').includes(:transaction_transfers).order(created_at: :desc)
    @rejected_transactions = Transaction.by_cash.where(status: 'rejected').includes(:transaction_transfers).order(created_at: :desc)
  end

  def approve
    redirect_to transactions_path and return unless @transaction
    @transaction.approve!
    @transaction.save
    redirect_to transactions_path
  end

  def reject
    redirect_to transactions_path and return unless @transaction
    @transaction.reject!
    @transaction.save
    redirect_to transactions_path
  end

  private
  def get_transaction
    @transaction = Transaction.where(id: params[:id]).first
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_other_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>User</th>
      <th>Type</th>
      <th>Asset</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% transactions.each_with_index do |transaction, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= transaction.name %></td>
        <td><%= transaction.user.email %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= transaction.asset_type %></td>
        <td><%= transaction.transaction_transfers_by('cash').first.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/_pending_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>User</th>
      <th>Type</th>
      <th>Asset</th>
      <th>Amount</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @transactions.each_with_index do |transaction, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= transaction.name %></td>
        <td><%= transaction.user.email %></td>
        <td><%= transaction.transaction_type %></td>
        <td><%= transaction.asset_type %></td>
        <td><%= transaction.transaction_transfers_by('cash').first&.amount %></td>
        <td>
          <%= link_to 'Approve', approve_transaction_path(transaction), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-info' %>
          <%= link_to 'Reject', reject_transaction_path(transaction), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transactions/index.html.erb
<div class="container">
  <h2>Transactions</h2>

  <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#pending">Pending</a></li>
    <li><a data-toggle="tab" href="#completed">Completed</a></li>
    <li><a data-toggle="tab" href="#rejected">Rejected</a></li>
  </ul>

  <div class="tab-content">
    <div id="pending" class="tab-pane fade in active">
      <h3>Pending</h3>
      <%= render 'pending_table' %>
    </div>
    <div id="completed" class="tab-pane fade">
      <h3>Completed</h3>
      <%= render partial: 'other_table', locals: {transactions: @completed_transactions} %>
    </div>
    <div id="rejected" class="tab-pane fade">
      <h3>Rejected</h3>
      <%= render partial: 'other_table', locals: {transactions: @rejected_transactions} %>
    </div>
  </div>
</div>